### ISSUE TITLE
"Collecting page data  ...Error: Cannot find module '../lib/prisma'" error  - Build error - Can't deploy!

### ISSUE THREAD

**Issue by prtpj1** [nikolasburk/blogr-nextjs-prisma#36]
Hi, I'm really trying to finish this tutorial, but there are a few issues in it.

I though I would finish it, I was near, the final steps, THE DEPLOY, BUT I was wrong.

After try the deploy following tutorial instructions I tried build locally.

And I got this error:
```
npm run build

> hello-next@1.0.0 build
> next build

 ✓ Linting and checking validity of types
   ▲ Next.js 14.0.4
   - Environments: .env

 ✓ Creating an optimized production build
 ✓ Compiled successfully
   Collecting page data  ...Error: Cannot find module '../lib/prisma'
Require stack:
- /home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/.next/server/pages/dist/drafts.js- /home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/node_modules/next/dist/server/require.js
- /home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/node_modules/next/dist/server/load-components.js
- /home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/node_modules/next/dist/build/utils.js
- /home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/node_modules/next/dist/build/worker.js
- /home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at /home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/cjs/helpers:121:18)
    at 1164 (/home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/.next/server/pages/dist/drafts.js:1:1838)
    at o (/home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/.next/server/webpack-runtime.js:1:127)
    at r (/home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/.next/server/pages/dist/drafts.js:1:5274)
    at /home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/.next/server/pages/dist/drafts.js:1:5301 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/.next/server/pages/dist/drafts.js',
    '/home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/node_modules/next/dist/server/require.js',
    '/home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/node_modules/next/dist/server/load-components.js',
    '/home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/node_modules/next/dist/build/utils.js',
    '/home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/node_modules/next/dist/build/worker.js',
    '/home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/node_modules/next/dist/compiled/jest-worker/processChild.js'
  ]
}

> Build error occurred
Error: Failed to collect page data for /dist/drafts
    at /home/prtpj/Trybe_U/Projetos/tutoriais/react/blogr-nextjs-prisma/node_modules/next/dist/build/utils.js:1220:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
   Collecting page data  .%
```
I did a few searchs and I tried:
rm -rf node_modules
npm install
npm install prisma@latest

I found this topics about it:
https://github.com/prisma/prisma/discussions/22374
https://github.com/prisma/prisma/discussions/21861

Then I tried and updated typescript to 5.2.2, but nothing worked.
![Screenshot_347](https://github.com/prisma/blogr-nextjs-prisma/assets/91347088/69a63615-ab26-4590-9e76-77c79f4e31cd)

There are other ways to try fix this issue?

**Comment by larry-xue** [comment]
hello, I had got this problem too, I find some document may be helpful in vercel's doc.
https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/vercel-caching-issue#a-custom-postinstall-script

you can add a script in your package.json: `"postinstall": "prisma generate"` to fix this error.

**Comment by larry-xue** [comment]
I believe the error you're encountering stems from using next@14, which introduces some breaking changes compared to next@12. The guide you're following is written for version next@12. You might want to consider downgrading to a lower version of next for compatibility.

![image](https://github.com/prisma/blogr-nextjs-prisma/assets/48818060/a682f4da-eec9-4b8e-9b6b-dec2126a18a0)

**Comment by prtpj1** [comment]
> I believe the error you're encountering stems from using next@14, which introduces some breaking changes compared to next@12. The guide you're following is written for version next@12. You might want to consider downgrading to a lower version of next for compatibility.
> 
> ![image](https://private-user-images.githubusercontent.com/48818060/302902587-a682f4da-eec9-4b8e-9b6b-dec2126a18a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjMzMzEsIm5iZiI6MTcwNzMyMzAzMSwicGF0aCI6Ii80ODgxODA2MC8zMDI5MDI1ODctYTY4MmY0ZGEtZWVjOS00YjhlLTliNmItZGVjMjEyNmExOGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE2MjM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZmU0M2RlMzA4MmE3ZTE0M2ZjZDE3M2FhOTE0N2EzOWRlNmY0MWNjOTkzZGQxM2ZlNDg0NTRlMTBmNmVkY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nTScItdBTZLdzrrHtaPaAiddLEp1w9IDo5Eyg5S46ag)

Hi Larry

Thx for reply.
I thought about downgrade, but as its a nextjs official tutorial I was hoping I could finish it even on a version superior to next12

So is it impossible or too much complicated?

And since there were breaking changes, the structure changes between 12 and 13...is it possible to do the downgrade from 14 to 12 without break everything?
Or I need to restart the tutorial using next12??

**Comment by larry-xue** [comment]
Hi Paulo,

You can take a look at the upgrade guide for nextjs first, and then decide whether to continue in the next@14.

 I think you can downgrade to version 12 first and then consider upgrading after completing the tutorial. If you haven't been learn next before, it will be difficult to handle version compatibility issues while studying the tutorial.

I hope these can help you
https://nextjs.org/docs/pages/building-your-application/upgrading

**Comment by prtpj1** [comment]
> Hi Paulo,
> 
> You can take a look at the upgrade guide for nextjs first, and then decide whether to continue in the next@14.
> 
> I think you can downgrade to version 12 first and then consider upgrading after completing the tutorial. If you haven't been learn next before, it will be difficult to handle version compatibility issues while studying the tutorial.
> 
> I hope these can help you https://nextjs.org/docs/pages/building-your-application/upgrading

I will think what path I will get.
I'm learning next and this was my second tutorial :D

Thx for the help...
